//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StickyNoteXUser
    {
        public int StickyUserID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StickynoteID { get; set; }
    
        public virtual StickyNote StickyNote { get; set; }
        public virtual User User { get; set; }
    }
}
